var backendErrorMessage = {
    BuildingNameRequired: 'Building Name is required.',
    LatitudeRequired: 'Latitude is required.',
    LongitudeRequired: 'Longitude is required.',
    DecimalLatitudeRequired: 'Latitude must be decimal number.',
    DecimalLongitudeRequired: 'Longitude must be decimal number.',
    BuildingDeleted: 'Building Deleted Successfully !!',
    BuildingUpdated: 'Building Updated Successfully !!',
    BuildingAdded: 'Building Added Successfully !!',
    FloorNameRequired: 'Floor Name is required.',
    FloorNoRequired: 'Floor No. is required.',
    UplaodValidJPG: 'Please upload valid JPG file',
    IssueOnImageUpload: 'Not able to Upload Image file successfully.',
    FloorUpdated: 'Floor Updated Successfully !!',
    FloorAdded: 'Floor Added Successfully !!',
    FloorRequired: 'Floor is required.',
    RoomNameRequired: 'Room Name is required.',
    ExchangeLocationRequired: 'Exchange Location is required.',
    AttendessRequired: 'No. of Attendees is required.',
    NearestAPNRequired: 'Nearest Access Point is required.',
    DirectionRequired: 'Direction is required.',
    RoomUpdated: 'Room Updated Successfully !!',
    RoomAdded: 'Room Added Successfully !!',
    ExchageRoomAlreadyMapped: 'Selected Exchange Room is already mapped with {RoomName}.Please Select Another Exchange Location !!',
    POINameRequired: 'POI name is required',
    POIUpdated: 'POI Updated Successfully !!',
    POIAdded: 'POI Added Successfully !!',
    APNameRequired: 'APName is required.',
    MacAddressRequired: 'Mac Address is required.',
    UploadValidCSVFile: 'Please Upload Valid CSV File.',
    UnableToReadCSVFile: 'Not able to read csv file successfully.',
    FloorLandmarkDeleted: 'Floor Landmark Deleted Successfully !!',
    FloorDeleted: 'Floor Deleted Successfully !!',
    RoomDeleted: 'Room Deleted Successfully !!',
    POIDeleted: 'Point of Interest Deleted Successfully !!',
    TagRequired: 'Tag is required',
    MessageRequired: 'Message is required',
    NotificationSend: 'Notification Send Successfully!!',
    UplaodValidKML: 'Upload Valid KML File.',
    SourceBuildingNameRequired: 'Source Building Name Required',
    DestinationBuildingNameRequired: 'Destination Building Name Required',
    SourceAndDestinationBuildingCannotBeSame: 'Source and Destination Building cannot be same.',
    BuildingDistanceAdded: 'Building Distance Added Successfully !!',
    BuildingDistanceUpdated: 'Building Distance Updated Successfully !!',
    NumericeAttendess: 'Enter valid value for Attendees',
    EnterValidEmail: "Enter valid Email Address",
    BuildingAlreadyExists: "Building Already Exists",
    FloorAlreadyExists: "Floor Already Exists",
    FloorLandmarkAlreadyExists: "Floor Landmark Already Exists",
    KMLImported: "KML Imported Successfully !!",
    PageTitleRequired: 'Page Title is required.',
    PageHeadingRequired: 'Page Heading is required.',
    PageContentRequired: 'Page Content is required.',
    EmailAddressRequired: 'Email Address is required.',
    ContactNORequired: 'Contact No. is required.',
    FAQPageUpdated: 'FAQ Page Detail Updated Successfully !!',
    FAQQuestionRquired: 'Question is required.',
    FAQAnswerRequired: 'Answer is required.',
    DisplayOrderRequired: 'Display Order is required.',
    FAQQAPageUpdated: 'FAQ Updated Successfully !!',
    FAQAdded: 'FAQ Added Successfully !!',
    FAQDeleted: "FAQ Deleted Successfully !!",
    SelectFile: 'Please select the file first.',
    ValidContactNoRequired: 'Please Enter Valid Contact No.',
}
module.exports = backendErrorMessage;
